version = 0.1

[default.deploy.parameters]
stack_name = "ami-api"
resolve_s3 = true
s3_prefix = "ami-api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
template_file = "sam-templates/template-lambda.yaml"
fail_on_empty_changeset = false

[default.global.parameters]
region = "us-east-1"
